/**
 * WOW-Market
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
@file:Suppress("ArrayInDataClass")

package com.example.common.vo.basic

/**
 *
 * @param title
 * @param status
 */
@kotlinx.serialization.Serializable
data class OperateError(
    var title: String? = null,
    var status: String? = null
)


/**
 *
 * @param errors
 * @param msg
 * @param error
 */
@kotlinx.serialization.Serializable
data class OperateResult(
    var errors: Array<OperateError>? = null,
    var msg: String? = null,
    var error: OperateError? = null
)
