/**
 * WOW-Market
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.example.common.vo


/**
 *
 * @param pageNumber
 * @param pageSize
 * @param order
 * @param pageTotal 仅响应使用
 * @param total 仅响应使用
 */
data class Page(
    val pageNumber: Int,
    val pageSize: Int,
    val order: String? = null,
    /* 仅响应使用 */
    val pageTotal: Int? = null,
    /* 仅响应使用 */
    val total: Int? = null
) 

